# Generated by Django 5.2.15 on 2026-06-29 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='compare_at_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category', verbose_name='categoría padre'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, verbose_name='tiene variantes'),
        ),
        migrations.AddField(
            model_name='product',
            name='hortitec_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='ID Hortitec'),
        ),
        migrations.AddField(
            model_name='product',
            name='outlet',
            field=models.BooleanField(default=False, verbose_name='outlet'),
        ),
        migrations.AddField(
            model_name='product',
            name='pvp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PVP'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='imagen principal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=220, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio compra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=260, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL en Hortitec'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.supplier', verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand', verbose_name='marca'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('hortitec_id', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='ID Hortitec')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='atributos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio compra')),
                ('pvp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PVP')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='imagen')),
                ('stock', models.BooleanField(default=True, verbose_name='en stock')),
                ('stock_level', models.CharField(blank=True, max_length=30, verbose_name='nivel stock')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'variante',
                'verbose_name_plural': 'variantes',
                'ordering': ['price'],
            },
        ),
    ]
