# Generated by Django 5.2.15 on 2026-06-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_remove_product_compare_at_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Mi Tienda', max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('free_shipping_from', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=5.95, max_digits=10)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
            ],
            options={
                'verbose_name': 'Configuración de la tienda',
                'verbose_name_plural': 'Configuración de la tienda',
            },
        ),
    ]
