# Generated by Django 5.2.15 on 2026-07-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='announcement_enabled',
            field=models.BooleanField(default=False, verbose_name='Mostrar aviso superior'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='announcement_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Texto del aviso'),
        ),
    ]
