# Generated by Django 5.2.15 on 2026-07-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_shopsettings_announcement_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden en la página principal'),
        ),
        migrations.AddField(
            model_name='category',
            name='home_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Título para la portada'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar en la página principal'),
        ),
    ]
